language: bash
services: docker

env:
  - VERSION=3.2 VARIANT=
  - VERSION=3.2 VARIANT=32bit
  - VERSION=3.2 VARIANT=alpine
  - VERSION=3.0 VARIANT=
  - VERSION=3.0 VARIANT=32bit
  - VERSION=3.0 VARIANT=alpine
  - VERSION=2.8 VARIANT=
  - VERSION=2.8 VARIANT=32bit

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="redis:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
