version: 2.1

commands:
  setup-executor:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
            bash <(curl -fsSL https://get.docker.com)
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

  checkout-all:
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive

  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            git submodule update --init deps/readies
            ./deps/readies/bin/getpy3

  prebuild:
    steps:
      - setup-executor
      - checkout-all
      - setup-automation
      - run:
          name: Setup Docker
          command: |
            docker login --username redisfab --password "$DOCKER_REDISFAB_PWD"

  vm-prebuild:
    steps:
      - checkout-all
      - setup-automation
      - run:
          name: Setup Docker
          command: |
            bash <(curl -fsSL https://get.docker.com)
            docker version
            docker login --username redisfab --password "$DOCKER_REDISFAB_PWD"

#----------------------------------------------------------------------------------------------------------------------------------

jobs:
  build-x64:
    parameters:
      platform:
        type: string
    docker:
      - image: 'debian:bullseye'
    steps:
      - prebuild
      - run:
          name: Build
          command: |
            docker version
            if [[ <<parameters.platform>> == mariner2.0 ]]; then
                make build OSNICK=<<parameters.platform>> VERSIONS="7.2 unstable"
            else
                make build OSNICK=<<parameters.platform>> STD_VERSIONS=1
            fi
          no_output_timeout: 30m
      - run:
          name: Publish
          command: |
            if [[ $CIRCLE_BRANCH == master ]]; then
              if [[ <<parameters.platform>> == mariner2.0 ]]; then
                make publish OSNICK=<<parameters.platform>> VERSIONS="7.2 unstable"
              else 
                make publish OSNICK=<<parameters.platform>> STD_VERSIONS=1
              fi
            else
                echo "Not master branch: skipped publish"
            fi

  build-arm8:
    parameters:
      platform:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - vm-prebuild
      - run:
          name: Build
          command: |
            docker version
            make build OSNICK=<<parameters.platform>> STD_VERSIONS=1
          no_output_timeout: 30m
      - run:
          name: Publish
          command: |
            if [[ $CIRCLE_BRANCH == master ]]; then
                make publish OSNICK=<<parameters.platform>> STD_VERSIONS=1
            else
                echo "Not master branch: skipped publish"
            fi

#----------------------------------------------------------------------------------------------------------------------------------

always: &always
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

#----------------------------------------------------------------------------------------------------------------------------------

workflows:
  version: 2
  general:
    jobs:
      - build-x64:
          <<: *always
          matrix:
            parameters:
              platform: [mariner2.0, amzn2023, amzn2, rocky9, rocky8, centos7, lunar, jammy, focal, bionic, xenial, bookworm, bullseye, buster, fedora] # alpine3, alpine
          context: common
      - build-arm8:
          <<: *always
          matrix:
            parameters:
              platform: [rocky9, rocky8, lunar, jammy, focal, bionic, bookworm, bullseye, buster, fedora] # alpine3, alpine
          context: common

  weekly:
    triggers:
      - schedule:
          # Run on Sundat 21:17 [M H DoM M DoW]
          cron: "21 17 * * 0"
          filters:
             branches:
               only: master
    jobs:
      - build-x64:
          matrix:
            parameters:
              platform: [mariner2.0, amzn2023, amzn2, rocky9, rocky8, centos7, lunar, jammy, focal, bionic, xenial, bookworm, bullseye, buster, fedora] # alpine3, alpine
          context: common
      - build-arm8:
          matrix:
            parameters:
              platform: [rocky9, rocky8, lunar, jammy, focal, bionic, bookworm, bullseye, buster, fedora] # alpine3, alpine
          context: common
